const proDashboardCards = [
  {
    id: 'card-001',
    playerName: 'Michael Jordan',
    cardTitle: '1986 Fleer Michael Jordan Rookie',
    image: 'https://ui-avatars.com/api/?name=Michael+Jordan&background=0d1b3e&color=f5a623',
    grader: 'PSA',
    grade: 10,
    value: 285000,
    status: 'Vaulted',
    date: '2026-05-30',
  },
  {
    id: 'card-002',
    playerName: 'LeBron James',
    cardTitle: '2003 Topps Chrome LeBron James Refractor',
    image: 'https://ui-avatars.com/api/?name=LeBron+James&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 9,
    value: 42500,
    status: 'For Sale',
    date: '2026-05-24',
  },
  {
    id: 'card-003',
    playerName: 'Kobe Bryant',
    cardTitle: '1996 Topps Chrome Kobe Bryant Rookie',
    image: 'https://ui-avatars.com/api/?name=Kobe+Bryant&background=0d1b3e&color=f5a623',
    grader: 'BGS',
    grade: 9.5,
    value: 18500,
    status: 'Watchlist',
    date: '2026-05-18',
  },
  {
    id: 'card-004',
    playerName: 'Stephen Curry',
    cardTitle: '2009 Topps Stephen Curry Rookie',
    image: 'https://ui-avatars.com/api/?name=Stephen+Curry&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 10,
    value: 9600,
    status: 'Vaulted',
    date: '2026-05-16',
  },
  {
    id: 'card-005',
    playerName: 'Victor Wembanyama',
    cardTitle: '2023 Prizm Victor Wembanyama Silver',
    image: 'https://ui-avatars.com/api/?name=Victor+Wembanyama&background=0d1b3e&color=f5a623',
    grader: 'Raw',
    grade: null,
    value: 780,
    status: 'Raw',
    date: '2026-05-12',
  },
  {
    id: 'card-006',
    playerName: 'Giannis Antetokounmpo',
    cardTitle: '2013 Prizm Giannis Antetokounmpo Rookie',
    image: 'https://ui-avatars.com/api/?name=Giannis+Antetokounmpo&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 9,
    value: 3400,
    status: 'Hold',
    date: '2026-05-09',
  },
  {
    id: 'card-007',
    playerName: 'Luka Doncic',
    cardTitle: '2018 Prizm Luka Doncic Rookie Silver',
    image: 'https://ui-avatars.com/api/?name=Luka+Doncic&background=0d1b3e&color=f5a623',
    grader: 'PSA',
    grade: 10,
    value: 5100,
    status: 'For Sale',
    date: '2026-05-06',
  },
  {
    id: 'card-008',
    playerName: 'Kevin Durant',
    cardTitle: '2007 Topps Chrome Kevin Durant Rookie',
    image: 'https://ui-avatars.com/api/?name=Kevin+Durant&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 9,
    value: 2200,
    status: 'Hold',
    date: '2026-05-03',
  },
  {
    id: 'card-009',
    playerName: 'Anthony Edwards',
    cardTitle: '2020 Prizm Anthony Edwards Rookie Silver',
    image: 'https://ui-avatars.com/api/?name=Anthony+Edwards&background=0d1b3e&color=f5a623',
    grader: 'Raw',
    grade: null,
    value: 640,
    status: 'Raw',
    date: '2026-04-30',
  },
  {
    id: 'card-010',
    playerName: 'Jayson Tatum',
    cardTitle: '2017 Prizm Jayson Tatum Rookie',
    image: 'https://ui-avatars.com/api/?name=Jayson+Tatum&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 10,
    value: 1250,
    status: 'Hold',
    date: '2026-04-26',
  },
  {
    id: 'card-011',
    playerName: 'Nikola Jokic',
    cardTitle: '2015 Prizm Nikola Jokic Rookie',
    image: 'https://ui-avatars.com/api/?name=Nikola+Jokic&background=0d1b3e&color=f5a623',
    grader: 'PSA',
    grade: 9,
    value: 2100,
    status: 'Vaulted',
    date: '2026-04-22',
  },
  {
    id: 'card-012',
    playerName: 'Shaquille ONeal',
    cardTitle: '1992 Topps Shaquille ONeal Rookie',
    image: 'https://ui-avatars.com/api/?name=Shaquille+ONeal&background=12244d&color=f5a623',
    grader: 'Raw',
    grade: null,
    value: 180,
    status: 'Raw',
    date: '2026-04-18',
  },
  {
    id: 'card-013',
    playerName: 'Tim Duncan',
    cardTitle: '1997 Topps Chrome Tim Duncan Rookie',
    image: 'https://ui-avatars.com/api/?name=Tim+Duncan&background=0d1b3e&color=f5a623',
    grader: 'PSA',
    grade: 9,
    value: 920,
    status: 'Hold',
    date: '2026-04-14',
  },
  {
    id: 'card-014',
    playerName: 'Allen Iverson',
    cardTitle: '1996 Topps Chrome Allen Iverson Rookie',
    image: 'https://ui-avatars.com/api/?name=Allen+Iverson&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 8,
    value: 430,
    status: 'Watchlist',
    date: '2026-04-10',
  },
  {
    id: 'card-015',
    playerName: 'Ja Morant',
    cardTitle: '2019 Prizm Ja Morant Rookie Silver',
    image: 'https://ui-avatars.com/api/?name=Ja+Morant&background=0d1b3e&color=f5a623',
    grader: 'PSA',
    grade: 9,
    value: 760,
    status: 'For Sale',
    date: '2026-04-06',
  },
  {
    id: 'card-016',
    playerName: 'Shai Gilgeous-Alexander',
    cardTitle: '2018 Prizm Shai Gilgeous-Alexander Rookie',
    image: 'https://ui-avatars.com/api/?name=Shai+Gilgeous-Alexander&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 10,
    value: 1450,
    status: 'Vaulted',
    date: '2026-04-02',
  },
  {
    id: 'card-017',
    playerName: 'Caitlin Clark',
    cardTitle: '2024 Panini Caitlin Clark Rated Rookie',
    image: 'https://ui-avatars.com/api/?name=Caitlin+Clark&background=0d1b3e&color=f5a623',
    grader: 'Raw',
    grade: null,
    value: 320,
    status: 'Raw',
    date: '2026-03-29',
  },
  {
    id: 'card-018',
    playerName: 'Dirk Nowitzki',
    cardTitle: '1998 Topps Chrome Dirk Nowitzki Rookie',
    image: 'https://ui-avatars.com/api/?name=Dirk+Nowitzki&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 9,
    value: 880,
    status: 'Hold',
    date: '2026-03-25',
  },
  {
    id: 'card-019',
    playerName: 'Dwyane Wade',
    cardTitle: '2003 Topps Chrome Dwyane Wade Rookie',
    image: 'https://ui-avatars.com/api/?name=Dwyane+Wade&background=0d1b3e&color=f5a623',
    grader: 'BGS',
    grade: 9,
    value: 1150,
    status: 'Hold',
    date: '2026-03-21',
  },
  {
    id: 'card-020',
    playerName: 'LaMelo Ball',
    cardTitle: '2020 Prizm LaMelo Ball Rookie Silver',
    image: 'https://ui-avatars.com/api/?name=LaMelo+Ball&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 9,
    value: 390,
    status: 'For Sale',
    date: '2026-03-17',
  },
  {
    id: 'card-021',
    playerName: 'Paolo Banchero',
    cardTitle: '2022 Prizm Paolo Banchero Rookie Silver',
    image: 'https://ui-avatars.com/api/?name=Paolo+Banchero&background=0d1b3e&color=f5a623',
    grader: 'Raw',
    grade: null,
    value: 240,
    status: 'Raw',
    date: '2026-03-13',
  },
  {
    id: 'card-022',
    playerName: 'Magic Johnson',
    cardTitle: '1980 Topps Magic Johnson Rookie',
    image: 'https://ui-avatars.com/api/?name=Magic+Johnson&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 7,
    value: 1700,
    status: 'Vaulted',
    date: '2026-03-09',
  },
  {
    id: 'card-023',
    playerName: 'Larry Bird',
    cardTitle: '1980 Topps Larry Bird Rookie',
    image: 'https://ui-avatars.com/api/?name=Larry+Bird&background=0d1b3e&color=f5a623',
    grader: 'PSA',
    grade: 7,
    value: 1650,
    status: 'Vaulted',
    date: '2026-03-05',
  },
  {
    id: 'card-024',
    playerName: 'Hakeem Olajuwon',
    cardTitle: '1986 Fleer Hakeem Olajuwon Rookie',
    image: 'https://ui-avatars.com/api/?name=Hakeem+Olajuwon&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 8,
    value: 1180,
    status: 'Watchlist',
    date: '2026-03-01',
  },
  {
    id: 'card-025',
    playerName: 'Charles Barkley',
    cardTitle: '1986 Fleer Charles Barkley Rookie',
    image: 'https://ui-avatars.com/api/?name=Charles+Barkley&background=0d1b3e&color=f5a623',
    grader: 'PSA',
    grade: 8,
    value: 980,
    status: 'Watchlist',
    date: '2026-02-25',
  },
  {
    id: 'card-026',
    playerName: 'Kawhi Leonard',
    cardTitle: '2012 Prizm Kawhi Leonard Rookie',
    image: 'https://ui-avatars.com/api/?name=Kawhi+Leonard&background=12244d&color=f5a623',
    grader: 'PSA',
    grade: 10,
    value: 1320,
    status: 'Hold',
    date: '2026-02-21',
  },
];

export default proDashboardCards;
